In [1]:
 import pandas as pd

In [2]:
data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Helen", "Ian", "Julia"],
    "Age": [25, 30, 35, 28, 45, 32, 29, 41, 27, 38],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 70000, 52000, 65000, 47000, 72000, 60000, 63000, 49000],
    "Experience": [2, 5, 10, 3, 15, 6, 12, 8, 4, 7],
    "City": ["New York", "Chicago", "Boston", "Seattle", "Miami", "Chicago", "Boston", "Seattle", "Miami", "New York"]
}

df = pd.DataFrame(data)

df

   Employee_ID     Name  Age Department  Salary  Experience      City
0          101    Alice   25         IT   50000           2  New York
1          102      Bob   30         HR   45000           5   Chicago
2          103  Charlie   35    Finance   70000          10    Boston
3          104    David   28         IT   52000           3   Seattle
4          105      Eva   45      Sales   65000          15     Miami
5          106    Frank   32         HR   47000           6   Chicago
6          107    Grace   29    Finance   72000          12    Boston
7          108    Helen   41         IT   60000           8   Seattle
8          109      Ian   27      Sales   63000           4     Miami
9          110    Julia   38         HR   49000           7  New York

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  10 non-null     int64
 1   Name         10 non-null     object
 2   Age          10 non-null     int64
 3   Department   10 non-null     object
 4   Salary       10 non-null     int64
 5   Experience   10 non-null     int64
 6   City         10 non-null     object
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes

In [4]:
print(df.head())

print(df.tail())

   Employee_ID     Name  Age Department  Salary  Experience      City
0          101    Alice   25         IT   50000           2  New York
1          102      Bob   30         HR   45000           5   Chicago
2          103  Charlie   35    Finance   70000          10    Boston
3          104    David   28         IT   52000           3   Seattle
4          105      Eva   45      Sales   65000          15     Miami
   Employee_ID   Name  Age Department  Salary  Experience      City
5          106  Frank   32         HR   47000           6   Chicago
6          107  Grace   29    Finance   72000          12    Boston
7          108  Helen   41         IT   60000           8   Seattle
8          109    Ian   27      Sales   63000           4     Miami
9          110  Julia   38         HR   49000           7  New York

In [6]:
df.shape

(10, 7)

In [7]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Department', 'Salary', 'Experience',
       'City'],
      dtype='object')

In [8]:
df.describe()

       Employee_ID        Age        Salary  Experience
count     10.00000  10.000000     10.000000   10.000000
mean     105.50000  33.000000  57300.000000    7.200000
std        3.02765   6.565905   9911.273043    4.131182
min      101.00000  25.000000  45000.000000    2.000000
25%      103.25000  28.250000  49250.000000    4.250000
50%      105.50000  31.000000  56000.000000    6.500000
75%      107.75000  37.250000  64500.000000    9.500000
max      110.00000  45.000000  72000.000000   15.000000

In [9]:
df[(df["Department"] == "HR") & (df["Salary"] > 46000)]

   Employee_ID   Name  Age Department  Salary  Experience      City
5          106  Frank   32         HR   47000           6   Chicago
9          110  Julia   38         HR   49000           7  New York